### PR TITLE
update deps

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by SamVerschueren** [comment]
Tests are failing, care to take a look?

**Comment by ghost** [comment]
Fails on Node 0.10, my guess is Pify, Node 0.10 is really old now....

**Comment by SamVerschueren** [comment]
Yes it is, but want to keep support as long as I don't have to write special Node 0.10 code.

@sindresorhus AVA used to come with Babel polyfills, is this removed in the latest version(s)?

**Comment by sindresorhus** [comment]
@SamVerschueren Yes, that was an oversight in previous AVA versions. Polyfilling libs causes subtle bugs that are impossible to detect until it's too late. We now only polyfill the testfile itself. You can fix this by changing line 12 to:

``` diff
- return pify(fs.writeFile)(file, fixture)
+ return pify(fs.writeFile, Promise)(file, fixture)
```

**Comment by SamVerschueren** [comment]
@sindresorhus Thanks for clarifying! :+1:

**Pull request merged**
